default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_API_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_API_ISSUER_ID"),
      key_content: ENV.fetch("APP_STORE_CONNECT_API_KEY"),
      is_key_content_base64: true,
      in_house: false
    )

    build_number = Time.now.utc.strftime("%Y%m%d%H%M")

    increment_build_number(
      xcodeproj: "apps/mobile2/ios/AdventurersLog.xcodeproj",
      build_number: build_number,
      skip_info_plist: true
    )

    set_info_plist_value(
      path: "apps/mobile2/ios/AdventurersLog/Info.plist",
      key: "CFBundleVersion",
      value: build_number
    )

    provisioning_profile = "OSRS Log App Store"

    build_app(
      workspace: "apps/mobile2/ios/AdventurersLog.xcworkspace",
      scheme: "AdventurersLog",
      configuration: "Release",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          app_identifier => provisioning_profile
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: false
    )
  end
end
