/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface AppMetadata {
  created_at: Generated<Timestamp>;
  key: string;
  value: Json;
}

export interface OsrsItems {
  examine: string | null;
  icon: string | null;
  id: number;
  members: boolean | null;
  name: string;
  raw_mapping: Json;
  updated_at: Generated<Timestamp>;
}

export interface PlayerSnapshots {
  created_at: Generated<Timestamp>;
  fetched_at: Timestamp;
  id: Generated<string>;
  normalized: Json;
  raw_player_snapshot_id: string;
  source: string;
  tracked_player_id: string;
}

export interface RawPlayerSnapshots {
  cached: boolean | null;
  created_at: Generated<Timestamp>;
  fetched_at: Timestamp;
  http_status: number | null;
  id: Generated<string>;
  raw_payload: Json;
  source: string;
  source_username: string;
  tracked_player_id: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface TrackedPlayers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  normalized_username: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  app_metadata: AppMetadata;
  osrs_items: OsrsItems;
  player_snapshots: PlayerSnapshots;
  raw_player_snapshots: RawPlayerSnapshots;
  session: Session;
  tracked_players: TrackedPlayers;
  user: User;
  verification: Verification;
}
