name: iOS CI

on:
  workflow_dispatch:
# on:
#   pull_request:
#   push:
#     branches: [main]

jobs:
  build-and-test:
    runs-on: [self-hosted, macOS]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install pnpm
        run: corepack enable
      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile
      - name: Install CocoaPods gem
        run: gem install cocoapods --no-document
      - name: Install CocoaPods
        working-directory: apps/mobile/ios
        run: pod install
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build
        run: |
          xcodebuild \
            -workspace apps/mobile/ios/AdventurersLog.xcworkspace \
            -scheme AdventurersLog \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            build
